apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: donetdemo.azurecr.io/myapp:latest   # ACR image
    imagePullSecrets:
    - name: acr-secret

          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer        # Expose to the internet
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80              # Service port
      targetPort: 80        # Container port
